# nom
name: e2e tests cypress et PHP
# declencheur
on:
  push:
    branches:
      - feature
  pull_request:
    branches:
      - feature
      - main
# environnement
jobs:
  build:
    # image unbuntu
    runs-on: ubuntu-latest
    # base de données
    services:
      # Service MySQL
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpw
          MYSQL_DATABASE: taskdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -prootpw"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5      
    # etape : checkout code
    steps:
      - name: checkout recuperation du code
        uses: actions/checkout@v6
      #install de php
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: pdo_mysql, intl, mbstring, zip
          tools: composer
      - name: installer les dépendances
        run: | 
          composer install
      - name: démarrer le serveur PHP
        run: |
          php -S 127.0.0.1:8000 -t public &

# job : build (environnemt du projet)
      - name: créer le .env
        run: |
          cp .env.docker .env

# compiler le code

# job : test (environnement du projet)
# installer cypress
      - name: Cypress run
        uses: cypress-io/github-action@v7
# lancer les tests cypress

